# =============================================================================
# Component: mev_ventilation.yaml
# Purpose:   MEV (Mechanical Extract Ventilation) coordinator with multi-demand
#            orchestration (CO2, IAQ, humidity) and humidity cascade state machine
#
# Required vars:
#   component_id                   - Prefix for entity IDs (e.g., "mev")
#   component_name                 - Friendly name prefix (e.g., "MEV")
#   power_relay                    - Relay ID for main power
#   mode_relay                     - Relay ID for winter/summer mode
#   dehumidifier_relay             - Relay ID for dehumidifier
#   cooling_relay                  - Relay ID for cooling integration
#   fan_speed_output               - DAC output ID for 0-10V fan speed
#   alarm_input                    - Binary sensor ID for alarm monitoring
#   humidity_sensor                - Sensor ID for humidity input
#   co2_sensor                     - Sensor ID for CO2 input
#   iaq_sensor                     - Sensor ID for IAQ input
#   cooling_mode_sensor            - Binary sensor ID for cooling season
#   min_fan_speed_entity           - HA entity for minimum fan speed
#   escalation_threshold_entity    - HA entity for escalation fan threshold
#   deescalation_threshold_entity  - HA entity for de-escalation fan threshold
#   escalation_delay_entity        - HA entity for escalation delay (minutes)
#   deescalation_delay_entity      - HA entity for de-escalation delay (minutes)
#   co2_lower_bound_entity         - HA entity for CO2 lower bound
#   co2_upper_bound_entity         - HA entity for CO2 upper bound
#   iaq_lower_bound_entity         - HA entity for IAQ lower bound
#   iaq_upper_bound_entity         - HA entity for IAQ upper bound
#   humidity_lower_bound_entity    - HA entity for humidity lower bound
#   humidity_upper_bound_entity    - HA entity for humidity upper bound
#
# Optional vars:
#   co2_rate_multiplier            - Rate boost for CO2 demand (default: 0.05)
#   iaq_rate_multiplier            - Rate boost for IAQ demand (default: 2.0)
#   humidity_rate_multiplier       - Rate boost for humidity demand (default: 20.0)
#
# Dependencies:
#   - ../utils/proportional_demand_sensor.yaml (3x, auto-included)
#     └── ../utils/trend_sensor.yaml (auto-included by each demand sensor)
#
# Humidity Cascade State Machine (event-driven with script delays):
#   Fan Only ──escalate──▶ Dehumidifying ──escalate──▶ Cooling
#   Fan Only ◀──de-escalate── Dehumidifying ◀──de-escalate── Cooling
#   (Cooling state only available in summer/cooling season)
#   Transitions use template binary sensors (condition evaluation) +
#   scripts with mode:restart (delay timers). on_press starts timer,
#   on_release cancels it.
#
# Exposes:
#   sensor.{component_id}_final_fan_speed       - Calculated fan speed (0-100%)
#   sensor.{component_id}_co2_demand            - CO2 demand % (via demand sensor)
#   sensor.{component_id}_iaq_demand            - IAQ demand % (via demand sensor)
#   sensor.{component_id}_humidity_demand       - Humidity demand % (via demand sensor)
#   text_sensor.{component_id}_dominant_demand  - Which demand is driving fan speed
#   text_sensor.{component_id}_automation_state - Current state machine status
#   select.{component_id}_humidity_state        - Humidity cascade state selector
#   number.{component_id}_fan_speed             - Fan speed control (0-100%)
#   switch.{component_id}_power                 - Main power switch
#   switch.{component_id}_mode                  - Winter/Summer mode switch
#   switch.{component_id}_dehumidifier          - Dehumidifier switch
#   switch.{component_id}_cooling               - Cooling integration switch
#   binary_sensor.{component_id}_alarm          - Alarm monitor
#
# Example:
#   packages:
#     mev: !include
#       file: packages/coordinators/mev_ventilation.yaml
#       vars:
#         component_id: "mev"
#         component_name: "MEV"
#         power_relay: relay_1
#         mode_relay: relay_2
#         dehumidifier_relay: relay_3
#         cooling_relay: relay_4
#         fan_speed_output: dac_1
#         alarm_input: input_1
#         humidity_sensor: bathroom_humidity
#         co2_sensor: living_room_co2
#         iaq_sensor: living_room_iaq
#         cooling_mode_sensor: summer_mode
#         min_fan_speed_entity: "input_number.mev_min_fan_speed"
#         escalation_threshold_entity: "input_number.mev_escalation_threshold"
#         deescalation_threshold_entity: "input_number.mev_deescalation_threshold"
#         escalation_delay_entity: "input_number.mev_escalation_delay"
#         deescalation_delay_entity: "input_number.mev_deescalation_delay"
#         co2_lower_bound_entity: "input_number.co2_lower_bound"
#         co2_upper_bound_entity: "input_number.co2_upper_bound"
#         iaq_lower_bound_entity: "input_number.iaq_lower_bound"
#         iaq_upper_bound_entity: "input_number.iaq_upper_bound"
#         humidity_lower_bound_entity: "input_number.humidity_lower_bound"
#         humidity_upper_bound_entity: "input_number.humidity_upper_bound"
# =============================================================================

defaults:
  co2_rate_multiplier: "0.05"
  iaq_rate_multiplier: "2.0"
  humidity_rate_multiplier: "20.0"

packages:
  co2_demand: !include
    file: ../utils/proportional_demand_sensor.yaml
    vars:
      component_id: ${component_id}
      component_name: ${component_name}
      demand_slug: co2
      demand_name: CO2
      unit_of_measurement: ppm
      source_sensor_id: ${co2_sensor}
      min_output_id: ${component_id}_min_fan_speed
      lower_bound_entity: ${co2_lower_bound_entity}
      upper_bound_entity: ${co2_upper_bound_entity}
      rate_multiplier: ${co2_rate_multiplier}
      icon: mdi:molecule-co2

  iaq_demand: !include
    file: ../utils/proportional_demand_sensor.yaml
    vars:
      component_id: ${component_id}
      component_name: ${component_name}
      demand_slug: iaq
      demand_name: IAQ
      unit_of_measurement: IAQ
      source_sensor_id: ${iaq_sensor}
      min_output_id: ${component_id}_min_fan_speed
      lower_bound_entity: ${iaq_lower_bound_entity}
      upper_bound_entity: ${iaq_upper_bound_entity}
      rate_multiplier: ${iaq_rate_multiplier}
      icon: mdi:air-filter

  humidity_demand: !include
    file: ../utils/proportional_demand_sensor.yaml
    vars:
      component_id: ${component_id}
      component_name: ${component_name}
      demand_slug: humidity
      demand_name: Humidity
      source_sensor_id: ${humidity_sensor}
      min_output_id: ${component_id}_min_fan_speed
      lower_bound_entity: ${humidity_lower_bound_entity}
      upper_bound_entity: ${humidity_upper_bound_entity}
      rate_multiplier: ${humidity_rate_multiplier}
      icon: mdi:water-percent

sensor:
  # Import configuration from HA
  - platform: homeassistant
    entity_id: ${escalation_threshold_entity}
    id: ${component_id}_escalation_threshold
    internal: true

  - platform: homeassistant
    entity_id: ${deescalation_threshold_entity}
    id: ${component_id}_deescalation_threshold
    internal: true

  - platform: homeassistant
    entity_id: ${min_fan_speed_entity}
    id: ${component_id}_min_fan_speed
    internal: true

  - platform: homeassistant
    entity_id: ${escalation_delay_entity}
    id: ${component_id}_escalation_delay
    internal: true

  - platform: homeassistant
    entity_id: ${deescalation_delay_entity}
    id: ${component_id}_deescalation_delay
    internal: true

  # Final Fan Speed (%) - MAX aggregation of all demands
  - platform: template
    name: "${component_name} Final Fan Speed"
    id: ${component_id}_final_fan_speed
    unit_of_measurement: "%"
    icon: mdi:fan-speed-3
    accuracy_decimals: 0
    update_interval: 60s
    lambda: |-
      if (id(${component_id}_alarm).state) {
        return 0.0f;
      }

      float co2 = id(${component_id}_co2_demand).state;
      float iaq = id(${component_id}_iaq_demand).state;
      float humidity = id(${component_id}_humidity_demand).state;
      float min_fan = id(${component_id}_min_fan_speed).state;

      // Fallback to min_fan if sensors are unavailable
      if (isnan(min_fan)) min_fan = 20.0f;
      float f_co2 = isnan(co2) ? min_fan : co2;
      float f_iaq = isnan(iaq) ? min_fan : iaq;
      float f_hum = isnan(humidity) ? min_fan : humidity;

      float final_speed = std::max({f_co2, f_iaq, f_hum, min_fan});

      // Update dominant demand diagnostics
      std::string dominant = "Ventilation";
      if (final_speed > min_fan) {
        if (final_speed == f_co2) dominant = "CO2";
        else if (final_speed == f_iaq) dominant = "IAQ";
        else if (final_speed == f_hum) dominant = "Humidity";
      }
      id(${component_id}_dominant_demand).publish_state(dominant);

      return std::min(100.0f, final_speed);
    on_value:
      then:
        - number.set:
            id: ${component_id}_fan_speed
            value: !lambda "return x;"

# Diagnostic Sensors
text_sensor:
  - platform: template
    name: "${component_name} Dominant Demand"
    id: ${component_id}_dominant_demand
    icon: mdi:gauge
    entity_category: diagnostic

  - platform: template
    name: "${component_name} Automation State"
    id: ${component_id}_automation_state
    icon: mdi:state-machine
    entity_category: diagnostic

# Humidity Cascade State Machine
select:
  - platform: template
    name: "${component_name} Humidity State"
    id: ${component_id}_humidity_state
    options:
      - "Fan Only"
      - "Dehumidifying"
      - "Cooling"
    initial_option: "Fan Only"
    optimistic: true
    restore_value: true
    set_action:
      - if:
          condition:
            lambda: 'return x == "Fan Only";'
          then:
            - switch.turn_off: ${component_id}_dehumidifier
            - switch.turn_off: ${component_id}_cooling
      - if:
          condition:
            lambda: 'return x == "Dehumidifying";'
          then:
            - switch.turn_on: ${component_id}_dehumidifier
            - switch.turn_off: ${component_id}_cooling
      - if:
          condition:
            lambda: 'return x == "Cooling";'
          then:
            - switch.turn_on: ${component_id}_dehumidifier
            - switch.turn_on: ${component_id}_cooling

# State Machine Scripts (with built-in delays)
# Scripts use mode: restart - restarting resets the delay timer.
# on_press starts the script, on_release stops it (cancels pending transition).
script:
  - id: ${component_id}_escalate_to_dehumidifying
    mode: restart
    then:
      - text_sensor.template.publish:
          id: ${component_id}_automation_state
          state: "Escalating (Dehum)"
      - delay: !lambda "return id(${component_id}_escalation_delay).state * 60000;"
      - select.set:
          id: ${component_id}_humidity_state
          option: "Dehumidifying"
      - logger.log:
          format: "MEV: Escalated to Dehumidifying"
          level: INFO
          tag: mev

  - id: ${component_id}_escalate_to_cooling
    mode: restart
    then:
      - text_sensor.template.publish:
          id: ${component_id}_automation_state
          state: "Escalating (Cooling)"
      - delay: !lambda "return id(${component_id}_escalation_delay).state * 60000;"
      - select.set:
          id: ${component_id}_humidity_state
          option: "Cooling"
      - logger.log:
          format: "MEV: Escalated to Cooling"
          level: INFO
          tag: mev

  - id: ${component_id}_deescalate_to_dehumidifying
    mode: restart
    then:
      - text_sensor.template.publish:
          id: ${component_id}_automation_state
          state: "De-escalating (Dehum)"
      - delay: !lambda "return id(${component_id}_deescalation_delay).state * 60000;"
      - select.set:
          id: ${component_id}_humidity_state
          option: "Dehumidifying"
      - logger.log:
          format: "MEV: De-escalated to Dehumidifying"
          level: INFO
          tag: mev

  - id: ${component_id}_deescalate_to_fan_only
    mode: restart
    then:
      - text_sensor.template.publish:
          id: ${component_id}_automation_state
          state: "De-escalating (Fan)"
      - delay: !lambda "return id(${component_id}_deescalation_delay).state * 60000;"
      - select.set:
          id: ${component_id}_humidity_state
          option: "Fan Only"
      - logger.log:
          format: "MEV: De-escalated to Fan Only"
          level: INFO
          tag: mev

  - id: ${component_id}_update_idle_state
    mode: restart
    then:
      - lambda: |-
          auto state = id(${component_id}_humidity_state).current_option();
          if (state == "Fan Only") {
            id(${component_id}_automation_state).publish_state("Idle");
          } else if (state == "Dehumidifying") {
            id(${component_id}_automation_state).publish_state("Dehumidifying");
          } else if (state == "Cooling") {
            id(${component_id}_automation_state).publish_state("Cooling");
          }

# Fan speed control (0-100% → 0-10V DAC)
number:
  - platform: template
    name: "${component_name} Fan Speed"
    id: ${component_id}_fan_speed
    icon: mdi:fan
    min_value: 0
    max_value: 100
    step: 1
    mode: slider
    unit_of_measurement: "%"
    optimistic: true
    restore_value: true
    initial_value: 0
    set_action:
      - output.set_level:
          id: ${fan_speed_output}
          level: !lambda "return x / 100.0;"

# Relay switches for hardware control
switch:
  - platform: template
    name: "${component_name} Power"
    id: ${component_id}_power
    icon: mdi:power
    optimistic: false
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - switch.turn_on: ${power_relay}
    turn_off_action:
      - switch.turn_off: ${power_relay}
    lambda: |-
      return id(${power_relay}).state;

  - platform: template
    name: "${component_name} Mode"
    id: ${component_id}_mode
    icon: mdi:thermometer
    optimistic: false
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - switch.turn_on: ${mode_relay}
    turn_off_action:
      - switch.turn_off: ${mode_relay}
    lambda: |-
      return id(${mode_relay}).state;

  - platform: template
    name: "${component_name} Dehumidifier"
    id: ${component_id}_dehumidifier
    icon: mdi:water-percent
    optimistic: false
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - switch.turn_on: ${dehumidifier_relay}
    turn_off_action:
      - switch.turn_off: ${dehumidifier_relay}
    lambda: |-
      return id(${dehumidifier_relay}).state;

  - platform: template
    name: "${component_name} Cooling"
    id: ${component_id}_cooling
    icon: mdi:snowflake
    optimistic: false
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - switch.turn_on: ${cooling_relay}
    turn_off_action:
      - switch.turn_off: ${cooling_relay}
    lambda: |-
      return id(${cooling_relay}).state;

# Alarm monitoring
binary_sensor:
  - platform: template
    name: "${component_name} Alarm"
    id: ${component_id}_alarm
    device_class: problem
    lambda: |-
      return id(${alarm_input}).state;
    on_press:
      then:
        - logger.log:
            level: ERROR
            format: "MEV ALARM DETECTED on %s"
            args: ['"${component_name}"']
        - number.set:
            id: ${component_id}_fan_speed
            value: 0
    on_release:
      then:
        - logger.log:
            level: INFO
            format: "MEV Alarm cleared on %s"
            args: ['"${component_name}"']

  # State Machine Transition Conditions (event-driven)
  - platform: template
    name: "${component_name} Should Escalate to Dehumidifying"
    id: ${component_id}_should_escalate_dehum
    internal: true
    lambda: |-
      auto state = id(${component_id}_humidity_state).current_option();
      float fan = id(${component_id}_final_fan_speed).state;
      float rate = id(${component_id}_humidity_rate).state;
      float thresh = id(${component_id}_escalation_threshold).state;
      if (isnan(fan) || isnan(rate) || isnan(thresh)) return false;
      return state == "Fan Only" && fan >= thresh && rate > 0.0f;
    on_press:
      - script.execute: ${component_id}_escalate_to_dehumidifying
    on_release:
      - script.stop: ${component_id}_escalate_to_dehumidifying
      - script.execute: ${component_id}_update_idle_state

  - platform: template
    name: "${component_name} Should Escalate to Cooling"
    id: ${component_id}_should_escalate_cooling
    internal: true
    lambda: |-
      auto state = id(${component_id}_humidity_state).current_option();
      float fan = id(${component_id}_final_fan_speed).state;
      float rate = id(${component_id}_humidity_rate).state;
      float thresh = id(${component_id}_escalation_threshold).state;
      bool summer = id(${cooling_mode_sensor}).state;
      if (isnan(fan) || isnan(rate) || isnan(thresh)) return false;
      return state == "Dehumidifying" && summer && fan >= thresh && rate > 0.0f;
    on_press:
      - script.execute: ${component_id}_escalate_to_cooling
    on_release:
      - script.stop: ${component_id}_escalate_to_cooling
      - script.execute: ${component_id}_update_idle_state

  - platform: template
    name: "${component_name} Should De-escalate to Dehumidifying"
    id: ${component_id}_should_deescalate_dehum
    internal: true
    lambda: |-
      auto state = id(${component_id}_humidity_state).current_option();
      float fan = id(${component_id}_final_fan_speed).state;
      float humidity = id(${humidity_sensor}).state;
      float lower = id(${component_id}_humidity_lower).state;
      float thresh = id(${component_id}_deescalation_threshold).state;
      bool summer = id(${cooling_mode_sensor}).state;
      if (isnan(fan) || isnan(humidity) || isnan(lower) || isnan(thresh)) return false;
      return state == "Cooling" && (!summer || (humidity < lower && fan < thresh));
    on_press:
      - script.execute: ${component_id}_deescalate_to_dehumidifying
    on_release:
      - script.stop: ${component_id}_deescalate_to_dehumidifying
      - script.execute: ${component_id}_update_idle_state

  - platform: template
    name: "${component_name} Should De-escalate to Fan Only"
    id: ${component_id}_should_deescalate_fan
    internal: true
    lambda: |-
      auto state = id(${component_id}_humidity_state).current_option();
      float fan = id(${component_id}_final_fan_speed).state;
      float humidity = id(${humidity_sensor}).state;
      float lower = id(${component_id}_humidity_lower).state;
      float thresh = id(${component_id}_deescalation_threshold).state;
      if (isnan(fan) || isnan(humidity) || isnan(lower) || isnan(thresh)) return false;
      return state == "Dehumidifying" && humidity < lower && fan < thresh;
    on_press:
      - script.execute: ${component_id}_deescalate_to_fan_only
    on_release:
      - script.stop: ${component_id}_deescalate_to_fan_only
      - script.execute: ${component_id}_update_idle_state
