# =============================================================================
# Component: trend_sensor.yaml
# Purpose:   Calculate rate of change per minute with sliding window smoothing
#
# Required vars:
#   sensor_id            - ID for the created trend sensor
#   source_sensor        - Sensor ID to analyze (e.g., sensor.room_temp)
#   unit_of_measurement  - Output unit (e.g., "°C/min", "%/min")
#
# Optional vars:
#   sensor_name          - Friendly name (default: "Trend Sensor")
#   window_size          - Smoothing window samples (default: 10)
#   accuracy_decimals    - Decimal precision (default: 2)
#   icon                 - MDI icon (default: "mdi:trending-up")
#   internal             - Hide from HA (default: false)
#
# Example:
#   packages:
#     trend: !include
#       file: packages/components/trend_sensor.yaml
#       vars:
#         sensor_id: "living_room_trend"
#         source_sensor: sensor.living_room_temperature
#         unit_of_measurement: "°C/min"
# =============================================================================

defaults:
  sensor_name: "Trend Sensor"
  accuracy_decimals: "2"
  window_size: "10"
  icon: "mdi:trending-up"
  internal: "false"

sensor:
  - platform: template
    id: ${sensor_id}
    name: "${sensor_name}"
    internal: ${internal}
    unit_of_measurement: "${unit_of_measurement}"
    accuracy_decimals: ${accuracy_decimals}
    icon: "${icon}"
    lambda: |-
      static float last_val = NAN;
      static uint32_t last_ts = 0;
      float cur_val = id(${source_sensor}).state;
      uint32_t now = millis();
      if (isnan(cur_val)) return NAN;
      float res = 0.0f;
      if (!isnan(last_val) && last_ts > 0 && now > last_ts) {
        float dt = (now - last_ts) / 60000.0f; // minutes
        if (dt > 0.01) res = (cur_val - last_val) / dt;
      }
      last_val = cur_val;
      last_ts = now;
      return res;
    filters:
      - sliding_window_moving_average:
          window_size: ${window_size}
          send_every: 1
