# =============================================================================
# Device Driver: modbus_analog_outputs_board.yaml
# Purpose:       Manage an 8-channel 0-10V Modbus analog output board. Creates
#                the modbus_controller, includes 8 analog output instances, and
#                monitors board connectivity via a status binary sensor.
#
# Required vars:
#   controller_id            - Unique ID for this modbus_controller
#   controller_name          - Display name for the status sensor (e.g., "Analog Board 1")
#   modbus_address           - Modbus slave address (e.g., 0x01)
#   modbus_bus_id            - ID of the modbus bus (e.g., "rs485_bus")
#
# Optional vars:
#   update_interval          - Polling interval (default: 1s — faster than relays
#                              for responsive analog control)
#   id_offset                - Offset for output IDs to avoid collisions across
#                              multiple boards (default: 0)
#
# Dependencies:
#   - modbus_analog_output.yaml (included automatically, must be in same directory)
#
# Exposes:
#   output.analog_output_{1+id_offset} through output.analog_output_{8+id_offset}
#   sensor.analog_output_{N}_capacity  - Per-channel capacity %
#   sensor.analog_output_{N}_voltage   - Per-channel voltage V
#   binary_sensor.${controller_id}_status - Board connectivity
#
# Example:
#   packages:
#     analog: !include
#       file: packages/devices/modbus-io/modbus_analog_outputs_board.yaml
#       vars:
#         controller_id: analog_board_1
#         controller_name: "Analog Board 1"
#         modbus_address: 0x01
#         modbus_bus_id: rs485_bus
# =============================================================================

defaults:
  update_interval: 1s
  id_offset: 0

modbus_controller:
  - id: ${controller_id}
    address: ${modbus_address}
    modbus_id: ${modbus_bus_id}
    update_interval: ${update_interval}

packages:
  output_1: !include
    file: modbus_analog_output.yaml
    vars:
      controller_id: ${controller_id}
      output_number: 1
      register_address: 0x0000
      id_offset: ${id_offset}
      update_interval: ${update_interval}
  output_2: !include
    file: modbus_analog_output.yaml
    vars:
      controller_id: ${controller_id}
      output_number: 2
      register_address: 0x0001
      id_offset: ${id_offset}
      update_interval: ${update_interval}
  output_3: !include
    file: modbus_analog_output.yaml
    vars:
      controller_id: ${controller_id}
      output_number: 3
      register_address: 0x0002
      id_offset: ${id_offset}
      update_interval: ${update_interval}
  output_4: !include
    file: modbus_analog_output.yaml
    vars:
      controller_id: ${controller_id}
      output_number: 4
      register_address: 0x0003
      id_offset: ${id_offset}
      update_interval: ${update_interval}
  output_5: !include
    file: modbus_analog_output.yaml
    vars:
      controller_id: ${controller_id}
      output_number: 5
      register_address: 0x0004
      id_offset: ${id_offset}
      update_interval: ${update_interval}
  output_6: !include
    file: modbus_analog_output.yaml
    vars:
      controller_id: ${controller_id}
      output_number: 6
      register_address: 0x0005
      id_offset: ${id_offset}
      update_interval: ${update_interval}
  output_7: !include
    file: modbus_analog_output.yaml
    vars:
      controller_id: ${controller_id}
      output_number: 7
      register_address: 0x0006
      id_offset: ${id_offset}
      update_interval: ${update_interval}
  output_8: !include
    file: modbus_analog_output.yaml
    vars:
      controller_id: ${controller_id}
      output_number: 8
      register_address: 0x0007
      id_offset: ${id_offset}
      update_interval: ${update_interval}

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${controller_id}
    name: "${controller_name} Status"
    id: ${controller_id}_status
    register_type: read
    address: 0x0000
    device_class: connectivity
    internal: true
